services:
  - type: web
    name: glpi-app
    runtime: docker
    repo: https://github.com/luizfilipeschaeffer/suporte
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        value: 172.20.0.2
      - key: DB_NAME
        value: glpi
      - key: DB_USER
        value: glpi_user
      - key: DB_PASSWORD
        value: glpi_password
